"""
Bakery Exporters - Calibration Data
===================================

Calibration data loading for INT8 quantization.

Extracted from calibrate_int8.py.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterator, Optional
import numpy as np

from bakery.catalog import config


class CalibrationDataLoader:
    """
    DataLoader for NNCF calibration.

    Loads pre-processed frames (.npy) for INT8 calibration.
    Frames should be generated by extract_calibration_frames.py.

    Usage:
        loader = CalibrationDataLoader(320)
        for frame in loader:
            # frame is np.ndarray with shape (1, 3, H, W)
            pass
    """

    def __init__(
        self,
        resolution: int,
        calibration_dir: Optional[Path] = None
    ):
        """
        Initialize calibration data loader.

        Args:
            resolution: Model resolution (320, 640, etc.)
            calibration_dir: Override calibration directory

        Raises:
            FileNotFoundError: If calibration data directory doesn't exist
            ValueError: If no frames found in directory
        """
        base_dir = calibration_dir or config.calibration_dir
        self.calibration_dir = base_dir / f"preprocessed_{resolution}"

        if not self.calibration_dir.exists():
            raise FileNotFoundError(
                f"Calibration data not found: {self.calibration_dir}\n"
                f"Run extract_calibration_frames.py first."
            )

        self.frame_files = sorted(self.calibration_dir.glob("*.npy"))

        if not self.frame_files:
            raise ValueError(f"No frames found in {self.calibration_dir}")

        print(f"   Loaded {len(self.frame_files)} frames for calibration")

    def __len__(self) -> int:
        """Return number of calibration frames."""
        return len(self.frame_files)

    def __iter__(self) -> Iterator[np.ndarray]:
        """Iterate over frames, loading on-demand."""
        for frame_file in self.frame_files:
            yield np.load(frame_file)


def discover_onnx_models(
    model_name: Optional[str] = None,
    resolution: Optional[int] = None
) -> list[dict]:
    """
    Discover ONNX models available for calibration.

    Args:
        model_name: Filter by model name (e.g., yolo26n-seg)
        resolution: Filter by resolution (320, 640)

    Returns:
        List of dicts with model info: {name, resolution, onnx_path}

    Raises:
        FileNotFoundError: If models directory doesn't exist
    """
    models = []

    if not config.models_dir.exists():
        raise FileNotFoundError(f"Directory not found: {config.models_dir}")

    # If model specified, search only that directory
    if model_name:
        model_dirs = [config.models_dir / model_name]
    else:
        model_dirs = [d for d in config.models_dir.iterdir() if d.is_dir()]

    for model_dir in sorted(model_dirs):
        if not model_dir.exists():
            continue

        name = model_dir.name

        # Search resolutions
        for res_dir in sorted(model_dir.iterdir()):
            if not res_dir.is_dir():
                continue

            try:
                res = int(res_dir.name)
            except ValueError:
                continue

            # Filter by resolution if specified
            if resolution and res != resolution:
                continue

            # Look for ONNX
            onnx_path = res_dir / "onnx" / "model.onnx"
            if onnx_path.exists():
                models.append({
                    "name": name,
                    "resolution": res,
                    "onnx_path": onnx_path,
                })

    return models
